displayName=Ruthless
author=Orinite
description=Ruthless Clan plugin for automating events and other information
tags=ruthless,clan,ruthlessosrs,ruthless.com
version=1.0.1
plugins=com.ruthless.RuthlessPlugin
build=standard